import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));
const oracle=JSON.parse(fs.readFileSync(path.join(dir,"deliberation-cases.json"),"utf8"));
const base={origin:"agent_detected_gap",fit:"not_satisfied",accepted_fit:["not_satisfied"],policy:"accepted",policy_freshness:"current",binding:"match",purpose:"match",epoch:"current",conditions:["satisfied"],coverage:"complete",duplicate:"none",intent:"none",access:"allowed"};
const answer=(result,reason)=>({result,reason});
const evaluate=overrides=>{
 const f={...base,...overrides};
 if(f.origin!=="agent_detected_gap") return answer("indeterminate",f.origin==="explicit_user_request"?"explicit_request_uses_direct_intent_path":f.origin==="existing_intent_drift"?"intent_drift_uses_fulfillment_path":f.origin==="routine_occurrence"?"routine_uses_instantiation_path":"safety_duty_uses_authority_procedure");
 if(f.fit==="indeterminate") return answer("indeterminate","target_fit_indeterminate");
 if(!f.accepted_fit.includes(f.fit)) return answer("not_eligible","fit_result_outside_policy");
 if(f.policy!=="accepted") return answer("indeterminate",`deliberation_policy_${f.policy}`);
 if(f.policy_freshness!=="current") return answer("indeterminate","deliberation_policy_not_current");
 if(f.binding!=="match") return answer("indeterminate","content_binding_mismatch");
 if(f.purpose!=="match") return answer("indeterminate","purpose_mismatch");
 if(f.epoch!=="current") return answer("indeterminate","authority_epoch_stale");
 if(f.access!=="allowed") return answer("indeterminate","condition_access_denied");
 if(f.duplicate==="indeterminate") return answer("indeterminate","duplicate_status_indeterminate");
 if(f.duplicate!=="none") return answer("not_eligible",`duplicate_${f.duplicate}`);
 if(f.intent==="adopted_for_exact_target") return answer("not_eligible","existing_intent_handles_exact_target");
 if(f.coverage!=="complete") return answer("indeterminate","condition_coverage_partial");
 if(f.conditions.includes("not_satisfied")) return answer("not_eligible","policy_condition_not_satisfied");
 if(f.conditions.includes("indeterminate")) return answer("indeterminate","policy_condition_indeterminate");
 return answer("eligible","accepted_gap_and_policy_conditions_satisfied");
};
assert.equal(oracle.cases.length,23);
for(const c of oracle.cases) assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);
for(const g of ["target_gap_is_need","eligible_creates_intent","eligible_adopts_intent","eligible_authorizes_notification","eligible_authorizes_action","duplicate_suppression_erases_gap","explicit_request_is_agent_inferred_need","intent_drift_is_new_opportunity","unknown_is_eligible"]) assert.ok(oracle.must_not_infer.includes(g),g);
console.log("DELIBERATION ELIGIBILITY OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("PATH SEPARATION OK","agent gap, explicit request, existing Intent drift, Routine occurrence, and safety duty remain distinct");
console.log("NO NEED OR INTERRUPTION OK","eligibility creates no Need, Intent adoption, notification permission, Proposal, Authorization, or action");
