import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));const oracle=JSON.parse(fs.readFileSync(path.join(dir,"closure-cases.json"),"utf8"));
const base={lifecycle:"transient",commitment:"adopted",binding:"match",coverage:"complete",expectations:"satisfied",optional:"satisfied",route:"task",exit:"satisfied",optional_exit:"satisfied",attempt:"none",attempt_policy:"resolved",obligation:"none",task_created_after:false,prior_fulfilled:false};
const answer=(intent,work,reason)=>({intent,work,reason});
const evaluate=o=>{const f={...base,...o};
 if(f.binding!=="match"){const r={intent_mismatch:"intent_binding_mismatch",view_mismatch:"world_view_binding_mismatch",realization_mismatch:"realization_binding_mismatch"}[f.binding];return answer("indeterminate","indeterminate",r)}
 if(f.commitment!=="adopted")return answer("not_evaluated","indeterminate","intent_not_adopted_for_realization_closure");
 let intent="fulfilled";
 if(f.coverage!=="complete")intent="indeterminate";
 else if(f.expectations==="not_satisfied")intent=f.lifecycle==="persistent"&&f.prior_fulfilled?"degraded":"not_fulfilled";
 else if(f.expectations==="indeterminate")intent="indeterminate";
 else if(f.expectations==="ongoing")intent="ongoing";
 let work="task_close_eligible",reason="assurance_and_task_exit_independently_satisfied";
 if(f.route==="direct")work="direct_realization_closed";
 if(f.task_created_after)return answer(intent,"indeterminate","direct_route_must_not_retroactively_create_task");
 if(f.obligation==="indeterminate")return answer(intent,"awaiting_evidence","post_action_obligation_indeterminate");
 if(f.obligation!=="none")return answer(intent,"task_remediation_required","post_action_obligation_open");
 if(f.attempt==="open")return answer(intent,"awaiting_evidence","open_attempt_blocks_closure");
 if(f.attempt==="delivery_unknown")return answer(intent,"awaiting_evidence","ambiguous_attempt_requires_reconciliation");
 if(f.attempt==="contested")return answer(intent,"awaiting_evidence","contested_attempt_blocks_closure");
 if(f.attempt==="failed"&&f.attempt_policy==="retry")return answer(intent,"task_continue_required","failed_attempt_requires_policy_work");
 if(f.attempt==="failed"&&f.attempt_policy==="remediate")return answer(intent,"task_remediation_required","failed_attempt_requires_remediation");
 if(f.exit==="indeterminate")return answer(intent,"awaiting_evidence","mandatory_task_exit_indeterminate");
 if(f.exit!=="satisfied")return answer(intent,"task_continue_required","mandatory_task_exit_not_satisfied");
 if(f.route==="direct")return answer(intent,work,"bounded_direct_realization_obligations_resolved");
 if(f.attempt==="failed")return answer(intent,work,"terminal_attempt_resolved_exit_satisfied");
 if(f.optional==="not_satisfied")return answer(intent,work,"optional_failure_does_not_mask_mandatory_success");
 if(f.lifecycle==="persistent"&&intent==="fulfilled")return answer(intent,work,"persistent_assurance_snapshot_task_close_eligible");
 if(intent==="not_fulfilled")return answer(intent,work,"intent_not_fulfilled_task_exit_independently_satisfied");
 if(intent==="degraded")return answer(intent,work,"persistent_drift_task_exit_independently_satisfied");
 if(intent==="indeterminate")return answer(intent,work,f.coverage!=="complete"?"assurance_window_incomplete_task_exit_satisfied":"intent_assurance_indeterminate_task_exit_satisfied");
 if(intent==="ongoing")return answer(intent,work,"intent_ongoing_task_exit_independently_satisfied");
 if(f.optional_exit==="not_satisfied")return answer(intent,work,"optional_exit_does_not_block_closure");
 return answer(intent,work,reason);};
assert.equal(oracle.cases.length,33);for(const c of oracle.cases)assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);
for(const x of ["intent_fulfilled_means_task_complete","task_close_eligible_closes_task","task_complete_means_intent_fulfilled","persistent_fulfilled_is_permanent","attempt_failed_fails_task","direct_route_creates_task_retroactively"])assert.ok(oracle.must_not_infer.includes(x));
console.log("OUTCOME ASSURANCE AND WORK CLOSURE OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("TWO AXES OK","Intent Assurance and Task closure remain independent");
console.log("OBLIGATION SAFETY OK","open attempts and post-action duties block work closure");
