import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));
const oracle=JSON.parse(fs.readFileSync(path.join(dir,"materialization-cases.json"),"utf8"));
const base={policy:"accepted",cross_proposal:"not_required",handoff:"not_required",alternatives:"not_required",review:"not_required",assumptions:"not_required",contingency:"not_required",task_method:"not_required",reference:"not_required",audit:"not_required",proposal:"complete",artifact:"structured",revision:"genesis",proposal_plan:"none",view:"match",epoch:"current",private_only:false,unlisted_alternative:false,plan_selected:false};
const answer=(result,reason)=>({result,reason});
const evaluate=o=>{
 const f={...base,...o};
 if(f.policy!=="accepted") return answer("indeterminate",`materialization_policy_${f.policy}`);
 if(f.view!=="match") return answer("indeterminate","world_view_binding_mismatch");
 if(f.epoch!=="current") return answer("indeterminate","authority_epoch_stale");
 if(f.revision==="mismatch") return answer("indeterminate","plan_revision_binding_mismatch");
 if(f.artifact==="raw_chain_of_thought") return answer("indeterminate","raw_chain_of_thought_not_portable_plan");
 if(f.artifact==="rationale_only") return answer("indeterminate","rationale_not_decision_structure");
 if(f.proposal!=="complete") return answer("indeterminate","proposal_not_self_contained");
 const factors=[f.cross_proposal,f.handoff,f.alternatives,f.review,f.assumptions,f.contingency,f.task_method,f.reference,f.audit];
 if(factors.includes("indeterminate")) return answer("indeterminate","downstream_reliance_indeterminate");
 if(f.cross_proposal==="required") return answer("plan_artifact_required","cross_proposal_dependencies_require_plan");
 if(f.handoff==="required") return answer("plan_artifact_required","handoff_or_continuity_requires_plan");
 if(f.alternatives==="required") return answer("plan_artifact_required","household_alternative_selection_requires_plan");
 if(f.review==="required") return answer("plan_artifact_required","method_review_requires_plan");
 if(f.assumptions==="required") return answer("plan_artifact_required","long_lived_assumptions_require_plan");
 if(f.contingency==="required") return answer("plan_artifact_required","cross_proposal_contingency_requires_plan");
 if(f.task_method==="required") return answer("plan_artifact_required","task_method_continuity_requires_plan");
 if(f.reference==="required") return answer("plan_artifact_required","explicit_plan_reference_requires_plan");
 if(f.audit==="required") return answer("plan_artifact_required","policy_audit_requires_plan");
 return answer("proposal_self_contained","no_downstream_method_reliance");
};
assert.equal(oracle.cases.length,24);
for(const c of oracle.cases) assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);
for(const g of ["private_reasoning_is_household_plan","chain_of_thought_is_faithful_proof","hidden_state_must_be_disclosed","missing_policy_defaults_ephemeral","unlisted_alternative_was_considered","plan_revision_retargets_proposal","plan_selected_authorizes_proposal","opaque_plan_can_hide_action_parameters","self_contained_proposal_skips_impact_review","plan_required_means_plan_already_exists"]) assert.ok(oracle.must_not_infer.includes(g),g);
console.log("PLAN MATERIALIZATION OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("DECISION STRUCTURE OK","portable Plan excludes raw prompts, hidden state, secrets, unrestricted context, and chain-of-thought");
console.log("PROPOSAL SELF-CONTAINMENT OK","Plan reliance never hides action parameters, preconditions, impacts, or authorization inputs");
