import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));
const oracle=JSON.parse(fs.readFileSync(path.join(dir,"proposal-lineage-cases.json"),"utf8"));
const base={revision:2,previous:"exact",sequence:"sequential",same_revision:"unique",identity:"same",alternative:"replace",change:"none",successors:1,retry:"none",downstream:"none",binding:"exact",state:"current",dispatch:false,authorization:"none"};
const answer=(result,reason)=>({result,reason});
const evaluate=o=>{
 const f={...base,...o};
 if(f.revision===1) return f.previous==="none"?answer("valid_genesis","genesis_has_no_predecessor"):answer("integrity_conflict","genesis_must_not_bind_predecessor");
 if(f.same_revision==="different_digest") return answer("integrity_conflict","same_revision_content_conflict");
 if(f.previous==="missing") return answer("indeterminate","exact_predecessor_unavailable");
 if(f.previous==="digest_mismatch") return answer("integrity_conflict","predecessor_digest_mismatch");
 if(f.sequence==="gap") return answer("integrity_conflict","revision_not_sequential");
 if(f.successors>1) return answer("contested","multiple_successors_of_exact_predecessor");
 if(f.identity!=="same") return answer("new_proposal_required","identity_basis_changed");
 if(f.alternative==="coexist") return answer("new_proposal_required","coexisting_alternative_needs_distinct_identity");
 if(f.dispatch && f.state!=="current") return answer("dispatch_denied","proposal_not_current");
 if(f.dispatch && f.binding==="exact" && f.authorization==="allowed") return answer("dispatch_eligible","current_and_exactly_authorized");
 if(f.downstream!=="none" && f.binding!=="exact") return answer("not_reusable","downstream_binding_not_exact");
 if(f.retry==="same_content") return answer("new_attempt","retry_does_not_change_proposal");
 if(f.retry==="changed_parameters") return answer("same_lineage_revision","changed_retry_content_requires_revision");
 if(f.change==="presentation") return answer("no_revision","noncanonical_presentation_changed");
 if(["parameters","preconditions","effects","impacts","world_view","plan","validity"].includes(f.change)) return answer("same_lineage_revision","mutable_proposal_content_changed");
 return answer("same_lineage_revision","exact_sequential_successor");
};
assert.equal(oracle.cases.length,33);
for(const c of oracle.cases) assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);
for(const g of ["proposal_id_identifies_mutable_command","timestamp_selects_fork","safer_successor_inherits_authorization","confirmation_carries_to_revision","authorization_carries_to_revision","proposal_supersession_erases_history","retry_is_proposal_revision","missing_digest_is_exact_binding"]) assert.ok(oracle.must_not_infer.includes(g),g);
console.log("ACTION PROPOSAL LINEAGE OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("EXACT BINDING OK","proposal id + revision + RFC8785/SHA-256 digest");
console.log("FORK SAFETY OK","multiple successors are contested; no last-writer-wins");
