import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));const oracle=JSON.parse(fs.readFileSync(path.join(dir,"review-cases.json"),"utf8"));
const base={fidelity:"preserved",coverage:"complete",procedure:"fit",rule:"fit",role:"satisfied",authorization:"allowed",ambiguity:"resolved",omission:"none",experience:"separate",population:"bounded",governance:"correct",purpose:"match",revision:"sequential",currency:"current",downstream:"none",author:"household"};
const a=(result,reason)=>({result,reason});
const evaluate=o=>{const f={...base,...o};
 if(f.revision==="conflict")return a("not_eligible","immutable_revision_content_conflict");if(f.revision==="gap")return a("indeterminate","proposal_revision_gap");if(f.currency!=="current")return a("revision_required","proposal_revision_not_current");
 if(f.purpose==="mismatch")return a("revision_required","proposal_not_fit_for_review_purpose");if(f.purpose!=="match")return a("indeterminate","review_purpose_binding_indeterminate");
 if(f.fidelity==="failed")return a("not_eligible","target_semantics_not_preserved");if(!["preserved","accepted_narrowing"].includes(f.fidelity))return a("indeterminate","target_semantic_fidelity_indeterminate");
 if(f.authorization==="denied")return a("not_eligible","evidence_use_not_authorized");if(f.authorization!=="allowed")return a("indeterminate","evidence_authorization_indeterminate");
 if(f.role==="missing")return a("not_eligible","required_reviewer_role_not_satisfied");if(f.role!=="satisfied")return a("indeterminate","reviewer_role_indeterminate");
 if(f.governance==="household_as_regulator")return a("not_eligible","reviewer_role_cannot_be_substituted");
 if(f.ambiguity==="defaulted")return a("not_eligible","agent_default_replaced_unresolved_meaning");if(f.ambiguity==="open")return a("revision_required","target_ambiguity_remains_open");if(f.ambiguity!=="resolved")return a("indeterminate","ambiguity_status_indeterminate");
 if(f.experience==="proxy")return a("not_eligible","sensor_proxy_cannot_replace_experience");if(f.population==="aggregate_as_universal")return a("revision_required","population_coverage_overclaimed");
 if(["subject","spatial","temporal","lifecycle","dimensions"].includes(f.coverage))return a("revision_required","declared_coverage_insufficient");if(f.coverage!=="complete")return a("indeterminate","coverage_indeterminate");
 if(f.procedure==="failed")return a("revision_required","evidence_procedure_not_fit");if(f.procedure!=="fit")return a("indeterminate","procedure_fitness_indeterminate");if(f.rule==="failed")return a("revision_required","decision_rule_not_fit");if(f.rule!=="fit")return a("indeterminate","decision_rule_fitness_indeterminate");
 if(f.omission==="undeclared")return a("revision_required","material_omission_undeclared");if(!["none","accepted"].includes(f.omission))return a("indeterminate","omission_status_indeterminate");
 if(f.downstream==="acceptance_requested")return a("eligible_for_acceptance","eligibility_requires_separate_authority_acceptance");return a("eligible_for_acceptance","proposal_fit_for_declared_purpose")};
assert.equal(oracle.cases.length,36);for(const c of oracle.cases)assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);assert.equal(oracle.must_not_infer.length,40);
for(const x of ["agent_draft_is_household_target","numeric_proxy_is_original_meaning","eligible_means_accepted","accepted_spec_means_satisfied","fit_creates_action_authorization"])assert.ok(oracle.must_not_infer.includes(x));
console.log("REQUIREMENT OPERATIONALIZATION OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("MEANING BOUNDARY OK","target expression, test proposal, review eligibility, specification acceptance, and fit remain distinct");
console.log("COVERAGE BOUNDARY OK","subject, space, time, lifecycle, dimension, experience, and reviewer roles remain explicit");
