import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));
const oracle=JSON.parse(fs.readFileSync(path.join(dir,"routing-cases.json"),"utf8"));
const base={intent:"adopted",policy:"accepted",scope:"match",view:"current",epoch:"current",occurrence:"one_off",existing_task:"none",proposal_count:"one",retry:"not_required",resume:"not_required",wait:"not_required",dependency:"not_required",handoff:"not_required",progress:"not_required",exit:"not_required",structure:"not_required",audit:"not_required",lifecycle:"transient",prior_direct:"none",agent_label:"none"};
const answer=(result,reason)=>({result,reason});
const evaluate=o=>{
 const f={...base,...o};
 if(f.intent!=="adopted") return answer("indeterminate","intent_not_adopted");
 if(f.policy!=="accepted") return answer("indeterminate",`routing_policy_${f.policy}`);
 if(f.scope!=="match") return answer("indeterminate","realization_scope_mismatch");
 if(f.view!=="current") return answer("indeterminate","world_view_not_current");
 if(f.epoch!=="current") return answer("indeterminate","authority_epoch_stale");
 if(f.existing_task==="indeterminate") return answer("indeterminate","existing_task_status_indeterminate");
 if(f.occurrence==="routine_occurrence") return answer("task_required","routine_occurrence_requires_task");
 if(f.existing_task==="open_exact_scope") return answer("task_required","existing_exact_task_cannot_be_bypassed");
 if([f.proposal_count,f.retry,f.resume,f.wait,f.dependency,f.handoff,f.progress,f.exit,f.structure,f.audit].includes("indeterminate")) return answer("indeterminate","work_shape_indeterminate");
 if(f.proposal_count==="multiple") return answer("task_required","multiple_proposals_require_lineage");
 if(f.retry==="required"||f.resume==="required") return answer("task_required","retry_or_resume_requires_lineage");
 if(f.wait==="required") return answer("task_required","asynchronous_wait_requires_lineage");
 if(f.dependency==="required") return answer("task_required","external_dependency_requires_lineage");
 if(f.handoff==="required") return answer("task_required","handoff_or_delegation_requires_lineage");
 if(f.progress==="required") return answer("task_required","durable_progress_requires_lineage");
 if(f.exit==="required") return answer("task_required","independent_exit_criteria_require_lineage");
 if(f.structure==="required") return answer("task_required","split_merge_or_reopen_requires_lineage");
 if(f.audit==="required") return answer("task_required","policy_audit_requires_task");
 return answer("direct_proposal_eligible",f.prior_direct==="failed"?"prior_direct_outcome_does_not_create_retry":"one_bounded_proposal_no_durable_identity_required");
};
assert.equal(oracle.cases.length,26);
for(const c of oracle.cases) assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);
for(const g of ["adopted_intent_always_creates_task","agent_simple_label_allows_direct","missing_policy_defaults_direct","direct_route_skips_impact_assessment","direct_route_authorizes_action","task_required_materializes_task","routine_occurrence_routes_direct","open_task_can_be_bypassed","direct_failure_creates_automatic_retry","new_work_shape_rewrites_old_assessment"]) assert.ok(oracle.must_not_infer.includes(g),g);
console.log("WORK REALIZATION ROUTING OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("DURABLE IDENTITY BOUNDARY OK","routing depends on accepted work-shape policy, not size, persistence, confidence, latency, or token count");
console.log("NO GOVERNANCE BYPASS OK","direct route omits only Task materialization and grants no Proposal or action authority");
