import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url));
const oracle=JSON.parse(fs.readFileSync(path.join(dir,"attempt-cases.json"),"utf8"));
const base={proposal:"exact",authorization:"current",currentness:"current",endpoint:"match",send:"none",dedupe:"none",payload:"same",ack:"none",late:false,effect:"not_evaluated",attempt_override:false};
const answer=(state,decision,reason)=>({state,decision,reason});
const evaluate=o=>{const f={...base,...o};
 if(f.proposal!=="exact")return answer("indeterminate","no_further_transmission","proposal_binding_mismatch");
 if(f.authorization!=="current")return answer("indeterminate","no_further_transmission","authorization_not_current");
 if(f.currentness!=="current")return answer("indeterminate","no_further_transmission","proposal_not_current");
 if(f.endpoint!=="match")return answer("indeterminate","no_further_transmission","endpoint_binding_mismatch");
 if(f.attempt_override)return answer("indeterminate","no_further_transmission","attempt_must_not_override_proposal");
 if(f.payload!=="same")return answer("contested","no_further_transmission","dedupe_key_payload_conflict");
 if(f.ack==="unknown_source")return answer("indeterminate","reconciliation_required","acknowledgement_source_untrusted");
 if(f.ack==="conflicting")return answer("contested","reconciliation_required","credible_execution_reports_conflict");
 if(f.ack==="completed_unverified")return answer("indeterminate","reconciliation_required","completion_report_not_admitted");
 if(f.ack==="completed_duplicate")return answer("execution_reported_completed","no_further_transmission","duplicate_report_collapsed");
 if(f.ack==="transport")return answer("delivery_unknown","reconciliation_required","transport_receipt_not_endpoint_acceptance");
 if(f.ack==="accepted")return answer("endpoint_accepted","no_further_transmission","endpoint_reported_acceptance");
 if(f.ack==="started")return answer("execution_reported_started","no_further_transmission","endpoint_reported_execution_started");
 if(f.ack==="completed")return answer("execution_reported_completed","no_further_transmission",f.late?"late_report_updates_new_assessment":"endpoint_reported_execution_completed");
 if(f.ack==="failed")return answer("execution_reported_failed","new_attempt_authorization_required","endpoint_reported_execution_failed");
 if(f.ack==="rejected")return answer("send_rejected","new_attempt_authorization_required","endpoint_rejected_execution");
 if(f.ack==="cancelled")return answer("cancellation_reported","no_further_transmission","endpoint_reported_cancellation_acceptance");
 if(f.send==="rejected")return answer("send_rejected","no_further_transmission","gateway_rejected_send");
 if(f.send==="proved_not_delivered")return answer("send_rejected","same_attempt_retransmission_allowed","non_delivery_proven");
 if(f.send==="timeout"){
  if(f.dedupe==="endpoint_current")return answer("delivery_unknown","same_attempt_retransmission_allowed","verified_endpoint_dedupe_window_open");
  if(f.dedupe==="endpoint_expired")return answer("delivery_unknown","reconciliation_required","endpoint_dedupe_window_expired");
  if(f.dedupe==="endpoint_contested")return answer("indeterminate","reconciliation_required","endpoint_dedupe_contract_contested");
  if(f.dedupe==="transport_only")return answer("delivery_unknown","reconciliation_required","transport_dedupe_not_endpoint_dedupe");
  return answer("delivery_unknown","reconciliation_required","possible_delivery_without_endpoint_dedupe");
 }
 return answer("not_sent","initial_send_allowed","authorized_current_proposal_ready");
};
assert.equal(oracle.cases.length,32);
for(const c of oracle.cases)assert.deepEqual(evaluate(c.facts),c.expected,c.case_id);
for(const x of ["timeout_means_not_delivered","transport_ack_means_endpoint_accepted","reported_completion_means_physical_effect","mqtt_qos2_means_physical_exactly_once","unknown_delivery_allows_new_attempt","attempt_can_override_proposal_parameters"])assert.ok(oracle.must_not_infer.includes(x));
console.log("ACTION ATTEMPT OK",oracle.cases.length,"semantic cases",oracle.must_not_infer.length,"forbidden inferences");
console.log("DELIVERY BOUNDARY OK","transport, endpoint report, observation, and effect remain separate");
console.log("RETRY SAFETY OK","unknown non-deduplicated delivery requires reconciliation");
